### ISSUE TITLE
List available options

### ISSUE THREAD

**Issue by rodolfoghi** [rodolfoghi/css-ptbr#4]

**Comment by iagolaguna** [comment]
Hello, i want to help you with this, maybe we can do something similar with this [w3schools](https://www.w3schools.com/Css/) does, look that link.

My suggest is that we create a list just like sidebar of w3schools with items with link to a content  where we will show the available options about this list item.

What are you think about that?

**Comment by rodolfoghi** [comment]
Great idea, can you implement the initial version?

**Comment by iagolaguna** [comment]
yes, i can, i gonna start implementation this week.

**Comment by iagolaguna** [comment]
Hello @rodolfoghi, i init the development of this issue,
look : https://github.com/iagolaguna/css-ptbr/blob/feature/improve-documentation/AVALIABLE-OPTIONS.md#alings , what think u about that layout? Is needed improve it, but i think that is good for fist

**Comment by rodolfoghi** [comment]
The layout is ok, just missing a column for the prefix.
It would be interesting if we could generate this file automatically. What do you think?

Example with prefix column.
![css-pt-br-avaliable-options](https://user-images.githubusercontent.com/9952024/42762051-a2e6eae2-88e5-11e8-905a-a3737fc465ec.PNG)

**Comment by rodolfoghi** [comment]
I am in doubt if this documentation should be in English or Portuguese, for users it is better in Portuguese, for contributors in English. Considering that the contributors know Portuguese, I think it is better to do it in Portuguese.

**Comment by iagolaguna** [comment]
i agree with you, this documentation must be in portuguese. If someone else want to contribute, speak portuguese is required to help.

**Comment by iagolaguna** [comment]
when i started to create this markdown, i think the same, create a cli that can read the name of files in snippets and create a list of that, and read the content of every file and create the table with the content,
but how stay unavaliable options?

**Comment by rodolfoghi** [comment]
Is necessary create new files with all options and compare if each option has included or not.

**Comment by iagolaguna** [comment]
that will be a painful job :cry:

**Comment by iagolaguna** [comment]
i research about that and this is beautiful, look that https://www.w3.org/Style/CSS/all-properties.en.json

**Comment by GuiDevloper** [comment]
Hey what's up. english is needed here? Only to know.
Needing help yet? I met the project suddenly and become interested after know more about.

**Comment by rodolfoghi** [comment]
Não precisa ser em inglês @GuiDevloper :)

Então, essa issue continua aberta, o @iagolaguna começou a trabalhar nela, mas não sei quanto evoluiu e ou se precisa de ajuda.
