### ISSUE TITLE
Add hyphens to translated property names

### ISSUE THREAD

**Issue by renanrodrigo** [rodolfoghi/css-ptbr#6]
I've applied the extension with some students and it really helped A LOT!
Most of the questions were about the hyphens: while the original css composite sentences, like `background-color` are separated by hyphens, `fundo cor` doesn't have the separator.
Is it intentional?

**Comment by rodolfoghi** [comment]
Well, honestly, I did not think much about the hyphens. For programmers, the hyphen makes sense, but for those who are starting I'm not sure.

We intend to develop more than one option for each property, for example for "background-color", we could have the options ```cor de fundo``` and ```cor fundo```, in addition to the existing ```fundo cor```, in this case not using hyphens could be seen as an advantage.

**Comment by renanrodrigo** [comment]
I think the hyphens are valuable when comparing the original css statements with the translated ones, helping the starters with programming patterns and standards. In a conversation with some students, we concluded that fomats like `cor-de-fundo` translating to `background-color` are accurate and respect cross-language rules.
Even if the hyphens aren't included, let me know if I can help with the translation and addition of new formats (:

**Comment by rodolfoghi** [comment]
Sure, just make the PR.

**Comment by rodolfoghi** [comment]
Now is possible use array of prefixes, can you implement and make PR?

See https://github.com/Microsoft/vscode/issues/42838

Sample:
## Before
```
    "background-color": {
        "body": "background-color:",
        "description": "Define a cor de fundo.",
        "prefix": "fundo cor"
    },
```
## After
```
    "background-color": {
        "body": "background-color:",
        "description": "Define a cor de fundo.",
        "prefix": ["fundo cor", "fundo-cor", "cor-fundo", "cor-de-fundo"]
    },
```

**Comment by renanrodrigo** [comment]
Yes!
I'll do it ASAP

**Comment by rodolfoghi** [comment]
The new version (0.0.9) has published on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=rghiggi.css-ptbr). Thanks @renanrodrigo for your contribution.
